### ISSUE TITLE
Migrate usdt attachment from bcc to libbpf

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#4151]
`AttachedProbe::attach_usdt()` uses bcc's `bpf_attach_uprobe()` to attach usdt probes (which are actually just backed by uprobes). This can be migrated to libbpf's `bpf_program__attach_uprobe()`.

Note that `attach_usdt()` makes use of a few other bcc APIs. This issue does not intend to migrate those usages to libbpf ones. That task would be much harder. It should be doable, though. We'll eventually do it, but sooner is better than later. Many bonus points if you can figure that out. This might need to be done in sync with other parts of the codebase like codegen.

**Comment by Phoenix500526** [comment]
I'm interesting in this issue, please assign it to me. @danobi

**Comment by Phoenix500526** [comment]
I noticed that there is an API named `bpf_program__attach_usdt` in libbpf. Why don't we migrate the `bpf_attach_uprobe` to the `bpf_program__attach_usdt`? @danobi @jordalgo

**Comment by Phoenix500526** [comment]
# TL;DR
The BCC and libbpf frameworks provide different methods for attaching USDT probes:

* BCC: Uses the `bpf_attach_uprobe` function, requiring manual calculation of the offset, handling of semaphores, and allows custom event names.

* libbpf: Provides the `bpf_program__attach_usdt` function, which automatically extracts USDT information from ELF files and handles offsets and semaphores, but does not support custom event names.

Their underlying implementations are similar, as both create probes using either the `perf_event_open` system call or tracefs. Libbpf is simpler and easier to use, but it does not support custom event names. I am unsure if this will impact previous releases.

---

The BCC framework doesn't provide a `bpf_attach_usdt` API. Therefore, if we want to use the BCC framework to attach a USDT probe, `bpf_attach_uprobe` is our only choice. However, libbpf provides an API called bpf_program__attach_usdt for USDT probe attachment. These two APIs are pasted as follows:

```C++
// BCC: bpf_attach_usdt
int bpf_attach_uprobe(int progfd, enum bpf_probe_attach_type attach_type,
                      const char *ev_name, const char *binary_path,
                      uint64_t offset, pid_t pid, uint32_t ref_ctr_offset);

// libbpf: bpf_program__attach_usdt
struct bpf_link *bpf_program__attach_usdt(const struct bpf_program *prog,
					  pid_t pid, const char *binary_path,
					  const char *usdt_provider, const char *usdt_name,
					  const struct bpf_usdt_opts *opts);

struct bpf_usdt_opts {
	/* size of this struct, for forward/backward compatibility */
	size_t sz;
	/* custom user-provided value accessible through usdt_cookie() */
	__u64 usdt_cookie;
	size_t :0;
};
```

To replace `bpf_attach_uprobe` with `bpf_program__attach_usdt`, we need to consider the following questions: 
1. What's the difference between their underlying implementations?
2. How to handle these three arguments: `ev_name`, `offset` and `ref_ctr_offset`? 


# How does the BCC framework attach a USDT probe?

## The underlying implementation of `bpf_attach_uprobe`

```C++
int bpf_attach_uprobe(int progfd, enum bpf_probe_attach_type attach_type,
                      const char *ev_name, const char *binary_path,
                      uint64_t offset, pid_t pid, uint32_t ref_ctr_offset)
{
  char archive_path[PATH_MAX];
  // update offset
  if (access(binary_path, F_OK) != 0 &&
      _find_archive_path_and_offset(binary_path, archive_path, &offset) == 0) {
    binary_path = archive_path;
  }

  return bpf_attach_probe(progfd, attach_type,
                          ev_name, binary_path, "uprobe",
                          offset, pid, -1, ref_ctr_offset);
}

static int bpf_attach_probe(int progfd, enum bpf_probe_attach_type attach_type,
                            const char *ev_name, const char *config1, const char* event_type,
                            uint64_t offset, pid_t pid, int maxactive,
                            uint32_t ref_ctr_offset)
{
  int kfd, pfd = -1;
  char buf[PATH_MAX], fname[256], kprobe_events[PATH_MAX];
  bool is_kprobe = strncmp("kprobe", event_type, 6) == 0;

  if (maxactive <= 0)
    // Try create the [k,u]probe Perf Event with perf_event_open API.
    // The offset and ref_ctr_offset are used here
    pfd = bpf_try_perf_event_open_with_probe(config1, offset, pid, event_type,
                                             attach_type != BPF_PROBE_ENTRY,
                                             ref_ctr_offset);
  // If failed, most likely Kernel doesn't support the perf_kprobe PMU
  // (e12f03d "perf/core: Implement the 'perf_kprobe' PMU") yet.
  // Try create the event using tracefs.
  if (pfd < 0) {
    if (create_probe_event(buf, ev_name, attach_type, config1, offset,
                           event_type, pid, maxactive) < 0)
      goto error;
    // omit kprobe relevant code...
  }

  // If perf_event_open succeeded, bpf_attach_tracing_event will use the created
  // Perf Event FD directly and buf would be empty and unused.
  // Otherwise it will read the event ID from the path in buf, create the
  // Perf Event event using that ID, and updated value of pfd.
  if (bpf_attach_tracing_event(progfd, buf, pid, &pfd) == 0)
    return pfd;

error:
  bpf_close_perf_event_fd(pfd);
  return -1;
}

/*
 * Kernel API with e12f03d ("perf/core: Implement the 'perf_kprobe' PMU") allows
 * creating [k,u]probe with perf_event_open, which makes it easier to clean up
 * the [k,u]probe. This function tries to create pfd with the perf_kprobe PMU.
 */
static int bpf_try_perf_event_open_with_probe(const char *name, uint64_t offs,
             int pid, const char *event_type, int is_return,
             uint64_t ref_ctr_offset)
{
  struct perf_event_attr attr = {};
  // omit some code ...
  attr.config |= (ref_ctr_offset << PERF_UPROBE_REF_CTR_OFFSET_SHIFT);

  /*
   * struct perf_event_attr in latest perf_event.h has the following
   * extension to config1 and config2. To keep bcc compatibe with
   * older perf_event.h, we use config1 and config2 here instead of
   * kprobe_func, uprobe_path, kprobe_addr, and probe_offset.
   *
   * union {
   *  __u64 bp_addr;
   *  __u64 kprobe_func;
   *  __u64 uprobe_path;
   *  __u64 config1;
   * };
   * union {
   *   __u64 bp_len;
   *   __u64 kprobe_addr;
   *   __u64 probe_offset;
   *   __u64 config2;
   * };
   */
  attr.config2 = offs;  /* config2 here is kprobe_addr or probe_offset */
  // omit some code...
  return syscall(__NR_perf_event_open, &attr, pid, cpu, -1 /* group_fd */,
                 PERF_FLAG_FD_CLOEXEC);
}
```

Generally speaking, `bpf_attach_uprobe` will first create a `perf_event` via the `perf_event_open` syscall or the `tracefs` filesystem, and then use `bpf_attach_tracing_event` to finish the attachment.

In those kernels that don't support perf_kprobe PMU, BCC will create perf_event via `tracefs`. It'll create a file at `format!("%s/uprobe_events", get_tracefs_path())` and store `format!("p:uprobe/%s %s:0x%lx", ev_alias, config1, (unsigned long)offset)` in it. 
While in those kernels that support perf_kprobe PMU, this `ev_name` will finally be ignored. 

BTW, the `offset` will be stored in the `perf_event.config2`， while the `ref_ctr_offset` will be stored in the high 32 bits of the relevant `perf_event.config`


## How does bpftrace use the BCC framework


The pseudocode for bpftrace's `AttachedUSDTProbe::make` is
```C++
Result<std::unique_ptr<AttachedUSDTProbe>> AttachedUSDTProbe::make(
    Probe &probe,
    const BpfProgram &prog,
    std::optional<int> pid) 
{
  // Step 1. generate a USDT::Context instance. It stores all the probe meta information
  auto *ctx = bcc_usdt_new_fromXXX();
  // Step 2. prepare the symbol offset
  struct bcc_usdt_location loc = {};
  int err = bcc_usdt_get_location(ctx,
                              probe.ns.c_str(),
                              probe.attach_point.c_str(),
                              probe.usdt_location_idx,
                              &loc);
  probe.loc = loc.address;
  auto offset_res = resolve_offset(probe);
  // Step 3. prepare the semaphore_offset.
  auto semaphore_offset = static_cast<uint32_t>(
      ctx->get(probe.ns.c_str(), probe.attach_point.c_str())->semaphore_offset);
  int perf_event_fd = bpf_attach_uprobe(prog.fd(),
                                        attachtype(probe.type),
                                        eventname(probe, offset).c_str(),
                                        probe.path.c_str(),
                                        offset,
                                        pid.has_value() ? *pid : -1,
                                        semaphore_offset);
  // omit some clean up code. 
}

std::string eventname(const Probe &probe, uint64_t offset)
{
  std::ostringstream offset_str;
  std::string index_str = "_" + std::to_string(probe.index);
  switch (probe.type) {
    // omit some code...
    case ProbeType::uprobe:
    case ProbeType::uretprobe:
    case ProbeType::usdt:
      offset_str << std::hex << offset;
      return eventprefix(probe.type) +
             util::sanitise_bpf_program_name(probe.path) + "_" +
             offset_str.str() + index_str;
    // omit some code...
  }
}

```
For a usdt probe, its `event_name` is `usdt_[sanitised_path]_[hex_offset]_[index]`


# How does `bpf_program__attach_usdt` attach a usdt probe?

```C++
struct bpf_link *bpf_program__attach_usdt(const struct bpf_program *prog,
					  pid_t pid, const char *binary_path,
					  const char *usdt_provider, const char *usdt_name,
					  const struct bpf_usdt_opts *opts)
{
	// omit some verify code...

	/* USDT manager is instantiated lazily on first USDT attach. It will
	 * be destroyed together with BPF object in bpf_object__close().
	 */
	if (!obj->usdt_man) {
		obj->usdt_man = usdt_manager_new(obj);
		// omit some error handle logic
	}

	usdt_cookie = OPTS_GET(opts, usdt_cookie, 0);
	link = usdt_manager_attach_usdt(obj->usdt_man, prog, pid, binary_path,
					usdt_provider, usdt_name, usdt_cookie);
	// omit some error handle logic
	return link;
}

struct usdt_manager *usdt_manager_new(struct bpf_object *obj)
{
	static const char *ref_ctr_sysfs_path = "/sys/bus/event_source/devices/uprobe/format/ref_ctr_offset";
	struct usdt_manager *man;

  // omit some code...

	/* Detect if BPF cookie is supported for kprobes.
	 * We don't need IP-to-ID mapping if we can use BPF cookies.
	 * Added in: 7adfc6c9b315 ("bpf: Add bpf_get_attach_cookie() BPF helper to access bpf_cookie value")
	 */
	man->has_bpf_cookie = kernel_supports(obj, FEAT_BPF_COOKIE);

	/* Detect kernel support for automatic refcounting of USDT semaphore.
	 * If this is not supported, USDTs with semaphores will not be supported.
	 * Added in: a6ca88b241d5 ("trace_uprobe: support reference counter in fd-based uprobe")
	 */
	man->has_sema_refcnt = faccessat(AT_FDCWD, ref_ctr_sysfs_path, F_OK, AT_EACCESS) == 0;
  
  // omit some code ...
	return man;
}

struct bpf_link *usdt_manager_attach_usdt(struct usdt_manager *man, const struct bpf_program *prog,
					  pid_t pid, const char *path,
					  const char *usdt_provider, const char *usdt_name,
					  __u64 usdt_cookie)
{
	unsigned long *offsets = NULL, *ref_ctr_offsets = NULL;
	int i, err, spec_map_fd, ip_map_fd;
	LIBBPF_OPTS(bpf_uprobe_opts, opts);
	struct hashmap *specs_hash = NULL;
	struct bpf_link_usdt *link = NULL;
	struct usdt_target *targets = NULL;
	__u64 *cookies = NULL;
	struct elf_fd elf_fd;
	size_t target_cnt;


	err = elf_open(path, &elf_fd);
	// omit error handling logic

	err = sanity_check_usdt_elf(elf_fd.elf, path);
	// omit error handling logic

	/* normalize PID filter */
	if (pid < 0)
		pid = -1;
	else if (pid == 0)
		pid = getpid();

	/* discover USDT in given binary, optionally limiting
	 * activations to a given PID, if pid > 0
	 */
	err = collect_usdt_targets(man, elf_fd.elf, path, pid, usdt_provider, usdt_name,
				   usdt_cookie, &targets, &target_cnt);

	// omit error handling logic

	link = calloc(1, sizeof(*link));
	// omit error handling logic

	link->usdt_man = man;
	link->link.detach = &bpf_link_usdt_detach;
	link->link.dealloc = &bpf_link_usdt_dealloc;

	if (man->has_uprobe_multi) {
		// omit some irrelevant logic...
	} else {
		link->uprobes = calloc(target_cnt, sizeof(*link->uprobes));
		// omit error handling logic...
	}

	for (i = 0; i < target_cnt; i++) {
		struct usdt_target *target = &targets[i];
		struct bpf_link *uprobe_link;
		bool is_new;
		int spec_id;

		/* Spec ID can be either reused or newly allocated. If it is
		 * newly allocated, we'll need to fill out spec map, otherwise
		 * entire spec should be valid and can be just used by a new
		 * uprobe. We reuse spec when USDT arg spec is identical. We
		 * also never share specs between two different USDT
		 * attachments ("links"), so all the reused specs already
		 * share USDT cookie value implicitly.
		 */
		err = allocate_spec_id(man, specs_hash, link, target, &spec_id, &is_new);
		if (err)
			goto err_out;

		if (is_new && bpf_map_update_elem(spec_map_fd, &spec_id, &target->spec, BPF_ANY)) {
			err = -errno;
			pr_warn("usdt: failed to set USDT spec #%d for '%s:%s' in '%s': %s\n",
				spec_id, usdt_provider, usdt_name, path, errstr(err));
			goto err_out;
		}
		if (!man->has_bpf_cookie &&
		    bpf_map_update_elem(ip_map_fd, &target->abs_ip, &spec_id, BPF_NOEXIST)) {
			err = -errno;
			if (err == -EEXIST) {
				pr_warn("usdt: IP collision detected for spec #%d for '%s:%s' in '%s'\n",
				        spec_id, usdt_provider, usdt_name, path);
			} else {
				pr_warn("usdt: failed to map IP 0x%lx to spec #%d for '%s:%s' in '%s': %s\n",
					target->abs_ip, spec_id, usdt_provider, usdt_name,
					path, errstr(err));
			}
			goto err_out;
		}

		if (man->has_uprobe_multi) {
			// omit some code ...
		} else {
			opts.ref_ctr_offset = target->sema_off;
			opts.bpf_cookie = man->has_bpf_cookie ? spec_id : 0;
			uprobe_link = bpf_program__attach_uprobe_opts(prog, pid, path,
								      target->rel_ip, &opts);
			err = libbpf_get_error(uprobe_link);
			// omit error handling logic
			link->uprobes[i].link = uprobe_link;
			link->uprobes[i].abs_ip = target->abs_ip;
			link->uprobe_cnt++;
		}
	}

	if (man->has_uprobe_multi) {
		// omit error handling logic
	}

	free(targets);
	hashmap__free(specs_hash);
	elf_close(&elf_fd);
	return &link->link;

err_out:
	// omit error handling logic
}

LIBBPF_API struct bpf_link *
bpf_program__attach_uprobe_opts(const struct bpf_program *prog, pid_t pid,
				const char *binary_path, size_t func_offset,
				const struct bpf_uprobe_opts *opts)
{
	// omit some code...
	func_name = OPTS_GET(opts, func_name, NULL);
	if (func_name) {
		long sym_off;

		if (archive_path) {
			sym_off = elf_find_func_offset_from_archive(archive_path, binary_path,
								    func_name);
			binary_path = archive_path;
		} else {
			sym_off = elf_find_func_offset_from_file(binary_path, func_name);
		}
		if (sym_off < 0)
			return libbpf_err_ptr(sym_off);
		func_offset += sym_off;
	}

	legacy = determine_uprobe_perf_type() < 0;
	switch (attach_mode) {
	case PROBE_ATTACH_MODE_LEGACY:
		legacy = true;
		pe_opts.force_ioctl_attach = true;
		break;
	case PROBE_ATTACH_MODE_PERF:
		if (legacy)
			return libbpf_err_ptr(-ENOTSUP);
		pe_opts.force_ioctl_attach = true;
		break;
	case PROBE_ATTACH_MODE_LINK:
		if (legacy || !kernel_supports(prog->obj, FEAT_PERF_LINK))
			return libbpf_err_ptr(-ENOTSUP);
		break;
	case PROBE_ATTACH_MODE_DEFAULT:
		break;
	default:
		return libbpf_err_ptr(-EINVAL);
	}

	if (!legacy) {
		pfd = perf_event_open_probe(true /* uprobe */, retprobe, binary_path,
					    func_offset, pid, ref_ctr_off);
	} else {
		char probe_name[MAX_EVENT_NAME_LEN];

		if (ref_ctr_off)
			return libbpf_err_ptr(-EINVAL);

		gen_probe_legacy_event_name(probe_name, sizeof(probe_name),
					    strrchr(binary_path, '/') ? : binary_path,
					    func_offset);

		legacy_probe = strdup(probe_name);
		if (!legacy_probe)
			return libbpf_err_ptr(-ENOMEM);

		pfd = perf_event_uprobe_open_legacy(legacy_probe, retprobe,
						    binary_path, func_offset, pid);
	}
	// omit error handling logic

	link = bpf_program__attach_perf_event_opts(prog, pfd, &pe_opts);
	err = libbpf_get_error(link);
	// omit error handling logic
	if (legacy) {
		struct bpf_link_perf *perf_link = container_of(link, struct bpf_link_perf, link);

		perf_link->legacy_probe_name = legacy_probe;
		perf_link->legacy_is_kprobe = false;
		perf_link->legacy_is_retprobe = retprobe;
	}
	return link;

err_clean_legacy:
  // omit error handling logic
err_out:
	// omit error handling logic
}

```
In short, `bpf_program__attach_usdt` manages USDT resources mainly via a `usdt_manager`. A `usdt_manager` is created when a USDT probe is first attached, and the attachment is finally completed by invoking `usdt_manager_attach_usdt`. By reading the implementation of usdt_manager_attach_usdt, we can see that `bpf_program__attach_usdt` ultimately attaches a USDT probe via `bpf_program__attach_uprobe_opts`.

However, `bpf_program__attach_uprobe_opts` will decide whether to use `perf_event_open` or `tracefs` to create a `perf_event` based on whether the mode is legacy or not.

In those kernels that don't support `perf_kprobe`, libbpf will crate `perf_event` via `perf_event_uprobe_open_legacy`. The key function is `add_uprobe_event_legacy`.

```C++
static inline int add_uprobe_event_legacy(const char *probe_name, bool retprobe,
					  const char *binary_path, size_t offset)
{
	return append_to_file(tracefs_uprobe_events(), "%c:%s/%s %s:0x%zx",
			      retprobe ? 'r' : 'p',
			      retprobe ? "uretprobes" : "uprobes",
			      probe_name, binary_path, offset);
}
```

As you can see, `add_uprobe_event_legacy` will create a `perf_event` via `tracefs`. The default `event_name` is `format!("p:uprobes/%s %s:0x%zx", probe_name, binary_path, offset)`. There is no way to customize this `event_name`.

# Conclusion

The underlying implementations of `bpf_program__attach_usdt` and `bpf_attach_uprobe` are similar. Both of them  finally finish the usdt probe attachment using `perf_kprobe` PMU mechanism or `tracefs`. The key differences lie in the processing of `offset`, `semaphore` and `event_name`.

The modified version of `AttachedUSDTProbe::make` may look like:

```C++
Result<std::unique_ptr<AttachedUSDTProbe>> AttachedUSDTProbe::make(
    Probe &probe,
    const BpfProgram &prog,
    std::optional<int> pid)
{
  auto *link = bpf_program__attach_usdt(prog.bpf_prog(),
                                        pid.has_value() ? *pid : -1,
                                        probe.path.c_str(),
                                        probe.ns.c_str(),
                                        probe.attach_point.c_str(),
                                        nullptr);

  if (!link) {
    char bpf_error_msg[128];
    int res = libbpf_strerror(errno, bpf_error_msg, sizeof(bpf_error_msg));
    if (res) {
      return make_error<AttachError>("Failed to attach usdt probe: " +
                                     std::string(std::strerror(errno)));
    } else {
      return make_error<AttachError>("Failed to attach usdt probe: " +
                                     std::string(bpf_error_msg));
    }
  }
  return std::unique_ptr<AttachedUSDTProbe>(new AttachedUSDTProbe(probe, link));
}
```

# Some other questions

1. Do we still need `USDTHelper`?
2. Migrating USDT attachment from BCC to libbpf means that we can no longer specify the `perf_event` file name. Will this have any impact on older versions of bpftrace?


@danobi @viktormalik @jordalgo

**Comment by jordalgo** [comment]
@Phoenix500526 Thanks for the write up.

As long as there are no external breakages in terms of the user-facing API of bpftrace, we can change any of the internals. So as long as we're not relying on `perf_event` for some user functionality, which should hopefully be exercised in a runtime test, we don't need to worry about keeping it. This goes for the `USDTHelper` as well. So I would suggest trying your modified version of the `AttachedUSDTProbe::make` and seeing if it passes CI. We also don't need to worry about any kernel versions less than 5.15 IMHO.

**Comment by Phoenix500526** [comment]
Unfortunately, the CI of pr #4217  failed. Although its error messages are very misleading, I found out the root cause. The libbpf provides two important maps named `__bpf_usdt_specs` and `__bpf_usdt_ip_to_spec_id` to store some usdt specific information. These two maps are defined in the header file `bpf/usdt.bpf.h` . This header file also includes some important functions, like `bpf_usdt_arg_size`, `bpf_usdt_arg_cnt`, etc. 

We need to "include" this header file into the BPF program. One possible way is to re-implement the map definition and those relevant helper functions in somewhere, maybe in the `codegen_llvm.cpp`. This way is straightforward but not elegant.

I think it is probably not the best practices. I'm not sure that there is any way to combine this header file with the generated bpf bytecode. What do you think? @jordalgo

**Comment by viktormalik** [comment]
Yeah, this is unfortunate. I think that until we have proper C interop (or at least a way to call BPF linker from inside bpftrace), we have no other choice but to reimplement those maps from codegen. Also if those maps differ for various versions of libbpf that we support, we'll need to maintain multiple versions of them. So, it's certainly not a long-term solution, the question is whether we should follow this path or rather invest in C interop or linker support.

@ajor I remember you did some work on the libbpf linker side, what's the status of that?

Also cc @amscanne who is AFAIK working on the C interop.

**Comment by ajor** [comment]
> [@ajor](https://github.com/ajor) I remember you did some work on the libbpf linker side, what's the status of that?

My libbpf change was just to support linking against in-memory objects instead of on-disk files, it's not made it into a libbpf release yet anyway: https://github.com/libbpf/libbpf/commit/d2f1f4490ba4a95efbeb6c62a632aef59a94437d

**Comment by jordalgo** [comment]
@Phoenix500526 - @amscanne and I are working through some possible solutions to this problem. Codegen, as you mentioned, might be a possibility but we want to see if we can leverage some of the newer C interop work. If you don't mind waiting a little bit we'll try to get back to you soon.

**Comment by Phoenix500526** [comment]
> [@Phoenix500526](https://github.com/Phoenix500526) - [@amscanne](https://github.com/amscanne) and I are working through some possible solutions to this problem. Codegen, as you mentioned, might be a possibility but we want to see if we can leverage some of the newer C interop work. If you don't mind waiting a little bit we'll try to get back to you soon.

Thanks for the update! I don’t mind waiting for your conclusions—please take your time. Looking forward to hearing more about the solution you’re exploring. 

Also, is there any discussion about the newer C interop work? I’d love to learn more or contribute if possible.

**Comment by amscanne** [comment]
So we've been talking about this and I think this is the sketch of things that need to happen for the migration:

- [x] #4228 and #4050 need to be landed. This can happen shortly, and will allow the implementation of C files to be linked into the BPF implementation.
- [x] We need to ensure that `libbpf` is statically linked. This is because the implementation of argument packing and unpacking is bound with the specific `libbpf` version that is used when defining the probes. If we embed the map and the associated specs into our C BPF standard library, we need to have the `libbpf` that populates this map be the same as the that one, therefore it has to statically linked into bpftrace. This is generally desirable: it is not large, and is a core dependency with a lot of specialization behavior that we depend on, so we should be linking it statically.
- [x] On top of #4228, we will need to embed `libbpf` headers (e.g. `bpf_helpers.h`, `usdt_bpf.h`) at build-time, e.g. using the `embed` CMake rule, and then make those available as part of the "stdlib". We don't need to build `libbpf` and can just slurp it out of the version used at build type, but it does need to be statically linked (above).
- [x] In the stdlib, we will need to define a file that includes `usdt_bpf.h` (as it has been embedded and made available above), and defines a trampoline for bpf_usdt_arg (basically just calls that function, but is exported). By including this header, it will also add the weak extern map references that will be used by `libbpf`. It's not clear if this file will need to be "imported" only if USDTs are used, but given that it is a weak ref I suspect that it will be fine to always be there.
- [ ] In generating the `argN` accesses for USDTs, this should instead emit a call to that trampoline function, which will read the cookie that has been set by `libbpf`, unpack the spec that has also been set by `libbpf`, and provide the argument.

Having these also means that we would be able to eliminate all the inline expansion that we currently have for USDTs, since `libbpf` uses a single program along with the specs to handle the different inline locations.

CC @viktormalik 

I think we still need to think through some of the details to see which parts can be done immediately (and which yaks should be shaved first), I'll follow up here soon.

**Comment by amscanne** [comment]
@Phoenix500526 I've pushed a stack that does some of the foundational pieces required for above. Currently #4276 is the top of that stack (that piece is a sketch). I will land the lower bits there, if you want to own that top piece it will need to be landed along with a move to `libbpf` (so that the arguments actually continue working).

**Comment by Phoenix500526** [comment]
@amscanne Sorry for the delay and thanks for the foundational work! I'm quite busy these days and won't be available until Sunday. I'll take a closer look at the changes and work on the USDT migration to libbpf after that. I understand this needs to be done together with the argument handling to ensure everything works properly. I'll keep you updated on the progress.

**Comment by jordalgo** [comment]
Thanks much @Phoenix500526 - This isn't a big rush but definitely something we want to complete in the next few months.

**Comment by Phoenix500526** [comment]
Hi, @amscanne @jordalgo 

I got a few questions:
1. What are the roles of the `base.bt` and `base.c` files in stdlib?
2. Although `usdt.bpf.h` has been embedded into stdlib, I still don't understand how to use it. 

I rebased PR #4217 to the latest changes, but after compilation, it still produced the same error: it couldn't find the `__bpf_usdt_ip_to_spec_id` and `__bpf_usdt_specs` maps. I debugged with gdb and found that in the `ResolveImports::importAny` function in `resolve_imports.cpp`, only `base.bt` is ultimately imported. Did I get something wrong?

**Comment by amscanne** [comment]
> I rebased PR https://github.com/bpftrace/bpftrace/pull/4217 to the latest changes, but after compilation, it still produced the same error: it couldn't find the __bpf_usdt_ip_to_spec_id and __bpf_usdt_specs maps. I debugged with gdb and found that in the ResolveImports::importAny function in resolve_imports.cpp, only base.bt is ultimately imported. Did I get something wrong?

As of 6556995cb8153141c76d789632cba68cde2d3afd, I believe that this is no longer the case. You will just need to name the C file `.bpf.c`.
